resources:
  pipelines:
  - pipeline: ms-iot.humble.release
    source: ms-iot.humble.release
    version: '220831.0006'

jobs:
- job: Signing
  pool: Edge-Robotics-VS2022-ESBuild
  variables:
    ROS_DISTRO: 'humble'
  timeoutInMinutes: 360
  workspace:
    clean: all
  steps:
  - download: ms-iot.humble.release
    artifact: humble-setup

  - task: EsrpCodeSigning@1
    inputs:
      ConnectedServiceName: 'ESRP Signing'
      FolderPath: $(PIPELINE.WORKSPACE)\ms-iot.humble.release\
      Pattern: '*.exe'
      signConfigType: 'inlineSignParams'
      inlineOperation: |
        [
          {
            "keyCode": "CP-232977",
            "operationSetCode": "SigntoolSign",
            "parameters": [
              {
                "parameterName": "OpusName",
                "parameterValue": "Microsoft"
              },
              {
                "parameterName": "OpusInfo",
                "parameterValue": "http://www.microsoft.com"
              },
              {
                "parameterName": "PageHash",
                "parameterValue": "/NPH"
              },
              {
                "parameterName": "FileDigest",
                "parameterValue": "/fd sha256"
              },
              {
                "parameterName": "TimeStamp",
                "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
              }
            ],
            "toolName": "signtool.exe",
            "toolVersion": "6.2.9304.0"
          }
        ]
      SessionTimeout: '360'
      MaxConcurrency: '50'
      MaxRetryAttempts: '5'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(PIPELINE.WORKSPACE)\ms-iot.humble.release'
      artifactName: 'ros-$(ROS_DISTRO)-setup-signed'
