trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - external/azure.pipelines.Ruby.yml
    - external/bootstrapRuby.ps1
    - external/wheels/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - external/azure.pipelines.Ruby.yml
    - external/bootstrapRuby.ps1
    - external/wheels/*

jobs:
- job: Build
  pool: Edge-Robotics-VS2022-ESBuild
  timeoutInMinutes: 360
  strategy:
    matrix:
      humble:
        INSTALL_DIR: 'c:\opt\ros\humble\x64'
        DISTRO_NAME: 'humble'
      rolling:
        INSTALL_DIR: 'c:\opt\ros\rolling\x64'
        DISTRO_NAME: 'rolling'
  workspace:
    clean: all
  steps:
  - powershell: |
      & .\external\bootstrapRuby310.ps1 -InstallDir $Env:INSTALL_DIR
    continueOnError: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(INSTALL_DIR)'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/Ruby.zip'
      replaceExistingArchive: true
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/Ruby.zip'
      artifactName: $(DISTRO_NAME)-Ruby
