trigger: none
pr: none

jobs:
- job: Vcpkg
  pool: Edge-Robotics-VS2022-ESBuild
  timeoutInMinutes: 360
  strategy:
    matrix:
      x64-windows:
        VCPKG_DEFAULT_TRIPLET: 'x64-windows'
  workspace:
    clean: all
  steps:
  - script: 'reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f'
    displayName: 'Enable long paths on Windows'
  - script: |
      git clone https://github.com/ms-iot/vcpkg.git -b humble
      call ".\vcpkg\bootstrap-vcpkg.bat"
      cd vcpkg
      dir
      vcpkg version
      vcpkg install @..\external\humble\vcpkg-core.in
    continueOnError: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '.\vcpkg\installed'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/installed.zip'
      replaceExistingArchive: true
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/installed.zip'
      artifactName: '$(VCPKG_DEFAULT_TRIPLET)-installed'
    continueOnError: true
